"""BigQuery schema definitions for ML model tables.

Defines schemas for:
- enla_callao_predictions_2026: Predictions generated by trained models
- enla_model_log: Audit trail for model training and prediction runs
"""

from google.cloud.bigquery import SchemaField
from typing import List, Dict


# ==========================================
# enla_callao_predictions_2026 schema
# Predictions from trained BQ ML models
# ==========================================
PREDICTIONS_SCHEMA: List[SchemaField] = [
    SchemaField("prediction_id", "STRING", mode="REQUIRED",
                description="Unique UUID for this prediction record"),
    SchemaField("area", "STRING", mode="REQUIRED",
                description="Subject area: comunicacion, matematica, ccss, cyt"),
    SchemaField("institution_id", "STRING", mode="REQUIRED",
                description="Institution ID (id_ie)"),
    SchemaField("nom_ie", "STRING", mode="NULLABLE",
                description="Institution name"),
    SchemaField("predicted_success", "INTEGER", mode="NULLABLE",
                description="Binary prediction: 1 (success) or 0 (failure)"),
    SchemaField("confidence", "FLOAT64", mode="NULLABLE",
                description="Prediction confidence/probability [0, 1]"),
    SchemaField("risk_level", "STRING", mode="NULLABLE",
                description="Risk classification: ALTO, MEDIO, BAJO"),
    SchemaField("model_version", "STRING", mode="NULLABLE",
                description="Model version string, e.g. 'v1'"),
    SchemaField("prediction_ts", "TIMESTAMP", mode="NULLABLE",
                description="Timestamp when prediction was generated"),
    SchemaField("created_at", "TIMESTAMP", mode="REQUIRED",
                description="Record creation timestamp"),
]


# ==========================================
# enla_model_log schema
# Audit trail for model training and prediction
# ==========================================
MODEL_LOG_SCHEMA: List[SchemaField] = [
    SchemaField("log_id", "STRING", mode="REQUIRED",
                description="Unique UUID for this log entry"),
    SchemaField("area", "STRING", mode="NULLABLE",
                description="Subject area (NULL for overall pipeline logs)"),
    SchemaField("operation", "STRING", mode="REQUIRED",
                description="Operation type: TRAIN, EVALUATE, PREDICT, SAVE"),
    SchemaField("model_version", "STRING", mode="NULLABLE",
                description="Model version string, e.g. 'v1'"),
    SchemaField("status", "STRING", mode="REQUIRED",
                description="Operation status: SUCCESS, FAILED, PARTIAL"),
    SchemaField("details", "STRING", mode="NULLABLE",
                description="JSON string with operation details (metrics, errors)"),
    SchemaField("duration_seconds", "FLOAT64", mode="NULLABLE",
                description="Operation duration in seconds"),
    SchemaField("created_at", "TIMESTAMP", mode="REQUIRED",
                description="Log entry timestamp"),
]


# ==========================================
# Schema registry for programmatic access
# ==========================================
MODEL_SCHEMA_REGISTRY: Dict[str, List[SchemaField]] = {
    "enla_callao_predictions_2026": PREDICTIONS_SCHEMA,
    "enla_model_log": MODEL_LOG_SCHEMA,
}


def get_model_schema(table_name: str) -> List[SchemaField]:
    """
    Get schema definition for a model-related table by name.

    Args:
        table_name: Table name key from MODEL_SCHEMA_REGISTRY

    Returns:
        List of SchemaField objects

    Raises:
        KeyError: If table_name is not in registry
    """
    if table_name not in MODEL_SCHEMA_REGISTRY:
        available = ", ".join(MODEL_SCHEMA_REGISTRY.keys())
        raise KeyError(f"Unknown model table '{table_name}'. Available: {available}")
    return MODEL_SCHEMA_REGISTRY[table_name]
